CREATE TABLE Players (
Id BIGINT NOT NULL IDENTITY PRIMARY KEY,
UserName VARCHAR(250) NOT NULL UNIQUE,
Grade TINYINT,
Created DATETIME2,
LoginFirst DATETIME2,
LoginLast DATETIME2
);

CREATE TABLE Levels (
Id BIGINT NOT NULL IDENTITY PRIMARY KEY,
LevelName VARCHAR(250) NOT NULL UNIQUE,
Difficulty TINYINT NOT NULL UNIQUE
);

CREATE TABLE Attempts (
Id BIGINT NOT NULL IDENTITY PRIMARY KEY,
PlayerId BIGINT NOT NULL FOREIGN KEY REFERENCES Players(Id),
LevelId BIGINT NOT NULL FOREIGN KEY REFERENCES Levels(Id),
StartedAt DATETIME2,
EndedAt DATETIME2
);