-- MySQL Script generated by MySQL Workbench
-- Thu Mar 12 14:07:45 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema graph_hopper
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema graph_hopper
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `graph_hopper` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `graph_hopper` ;

-- -----------------------------------------------------
-- Table `graph_hopper`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graph_hopper`.`players` (
  `player_id` INT NOT NULL AUTO_INCREMENT,
  `google_id` INT NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  `grade` INT NULL DEFAULT NULL,
  `created_ts` DATETIME NOT NULL DEFAULT now(),
  `login_first_ts` DATETIME NULL DEFAULT NULL,
  `login_last_ts` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`player_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `graph_hopper`.`levels`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graph_hopper`.`levels` (
  `level_id` INT NOT NULL AUTO_INCREMENT,
  `level_name` VARCHAR(255) NULL DEFAULT NULL,
  `difficulty` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`level_id`),
  UNIQUE INDEX `level_name` (`level_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `graph_hopper`.`attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `graph_hopper`.`attempts` (
  `attempt_id` INT NOT NULL AUTO_INCREMENT,
  `player_id` INT NULL DEFAULT NULL,
  `level_id` INT NULL DEFAULT NULL,
  `attempt_num` INT NULL DEFAULT NULL,
  `started_ts` TIMESTAMP NULL DEFAULT now(),
  `ended_ts` TIMESTAMP NULL DEFAULT NULL,
  `success` TINYINT(1) NULL DEFAULT NULL,
  `score` INT NULL DEFAULT NULL,
  `code_changes` INT NULL DEFAULT NULL,
  `start_code` VARCHAR(255) NULL DEFAULT NULL,
  `end_code` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`attempt_id`),
  INDEX `player_id` (`player_id` ASC) VISIBLE,
  INDEX `level_id` (`level_id` ASC) VISIBLE,
  CONSTRAINT `attempts_ibfk_1`
    FOREIGN KEY (`player_id`)
    REFERENCES `graph_hopper`.`players` (`player_id`),
  CONSTRAINT `attempts_ibfk_2`
    FOREIGN KEY (`level_id`)
    REFERENCES `graph_hopper`.`levels` (`level_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
